baseURL = 'https://kuadrant.github.io/'
languageCode = 'en-us'
title = 'kuadrant.io'

[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"
[[module.imports]]
path = "github.com/google/docsy/dependencies"
