name: Eleventy Build
on:
  push:
    branches: [main]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: Build
        uses: TartanLlama/actions-eleventy@master
        with:
          install_dependencies: true
          args: --output _site
      - name: Find
        run: find .
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: _site
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: kuadrant.io
